### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmgeneration#111]
when i train the stylegan2_c2_ffhq_512_b3x8_1100k using bash tools/dist_train.sh configs/positional_encoding_in_gans/stylegan2_c2_ffhq_512_b3x8_1100k.py 1

i meet the problem:
 Traceback (most recent call last):
  File "tools/train.py", line 163, in <module>
    main()
  File "tools/train.py", line 159, in main
    meta=meta)
  File "/home/wenjun/mmgeneration/mmgen/apis/train.py", line 198, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/wenjun/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/wenjun/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/wenjun/mmgeneration/mmgen/models/gans/static_unconditional_gan.py", line 175, in train_step
    disc_pred_real = self.discriminator(real_imgs)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wenjun/mmgeneration/mmgen/core/runners/fp16_utils.py", line 142, in new_func
    return old_func(*args, **kwargs)
  File "/home/wenjun/mmgeneration/mmgen/models/architectures/stylegan/generator_discriminator_v2.py", line 605, in forward
    x = self.final_linear(x)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wenjun/mmgeneration/mmgen/models/architectures/stylegan/modules/styleganv2_modules.py", line 105, in forward
    x = self.linear(x)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0
Killing subprocess 32428
Traceback (most recent call last):
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/wenjun/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/wenjun/anaconda3/envs/mmgeneration/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'configs/positional_encoding_in_gans/stylegan2_c2_ffhq_512_b3x8_1100k.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

can you help me?
Thans!

**Comment by nbei** [comment]
Hi @wwjwy , can you print the size of the input image for the discriminator? It seems that the discriminator receives an input with wrong shapes.

**Comment by wwjwy** [comment]
> Hi @wwjwy , can you print the size of the input image for the discriminator? It seems that the discriminator receives an input with wrong shapes.

Thank you very much, it works now.

**Comment by 19990101lrk** [comment]
> > Hi @wwjwy , can you print the size of the input image for the discriminator? It seems that the discriminator receives an input with wrong shapes.
> 
> Thank you very much, it works now.

I encountered the same problem, how did you solve it?
