### ISSUE TITLE
fused_bias_leakyrelu(): incompatible function arguments. The following argument types are supported:     1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: int, arg4: int, arg5: float, arg6: float) -> at::Tensor

### ISSUE THREAD

**Issue by wj-data** [open-mmlab/mmgeneration#15]
**Describe the bug**
On Ubuntu20.04, NVIDIA RTX 3080, Python3.8, I run the official [varification demo](https://mmgeneration.readthedocs.io/en/latest/get_started.html#verification), but get the `TypeError`

```python
from mmgen.apis import init_model, sample_uncoditional_model
if __name__ == '__main__':
    config_file = 'configs/styleganv2/stylegan2_c2_lsun-church_256_b4x8_800k.py'
    # you can download this checkpoint in advance and use a local file path.
    checkpoint_file = 'http://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-church-config-f-official_20210327_172657-1d42b7d1.pth'
    device = 'cuda:0'
    # init a generatvie
    model = init_model(config_file, checkpoint_file, device=device)
    # sample images
    fake_imgs = sample_uncoditional_model(model, 4)
    print(fake_imgs)
```
error infomation:
```sh
    out = ext_module.fused_bias_leakyrelu(
TypeError: fused_bias_leakyrelu(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: int, arg4: int, arg5: float, arg6: float) -> at::Tensor

Invoked with: tensor([[ 1.5543,  0.9359, -0.7516,  ...,  0.8526,  0.1092, -1.5828],
        [-0.4884, -0.5331,  0.0995,  ..., -1.1292,  0.7263,  0.0868],
        [ 1.8955, -0.2950, -0.6122,  ..., -1.5320,  0.3621, -0.0334],
        [-1.1611,  1.4324, -0.5950,  ..., -0.0754, -0.2390,  0.5369]],
       device='cuda:0'), tensor([ 2.1072e-02,  7.2350e-03, -7.3995e-03,  8.8704e-03,  1.2794e-02,
         ...
        -1.4140e-03, -4.1711e-03,  1.9475e-02, -4.1921e-03,  4.0421e-03,
         6.0400e-03, -4.2922e-03], device='cuda:0'), tensor([], device='cuda:0'); kwargs: act=3, grad=0, alpha=0.2, scale=1.4142135623730951
```
I debug the input 7 args, their data type all are right, but when I change the `device="cuda:0"` to `device=cpu`, it works fine, just like below
```python
from mmgen.apis import init_model, sample_uncoditional_model

if __name__ == '__main__':
    config_file = 'configs/styleganv2/stylegan2_c2_lsun-church_256_b4x8_800k.py'
    # you can download this checkpoint in advance and use a local file path.
    checkpoint_file = 'http://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-church-config-f-official_20210327_172657-1d42b7d1.pth'
    device = 'cpu'
    # init a generatvie
    model = init_model(config_file, checkpoint_file, device=device)
    # sample images
    fake_imgs = sample_uncoditional_model(model, 4)
    print(fake_imgs)
```

**Environment**

sys.platform: linux
Python: 3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Build cuda_11.1.TC455_06.29069683_0
GPU 0: GeForce RTX 3080
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.0
OpenCV: 4.5.1
MMCV: 1.3.2
MMGen: 0.1.0+d7eda0b
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1

**Error traceback**
Traceback (most recent call last):
  File "/usrpath/data/openmmlab/mmgeneration/my_test.py", line 11, in <module>
    fake_imgs = sample_uncoditional_model(model, 4)
  File "/usrpath/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usrpath/data/openmmlab/mmgeneration/mmgen/apis/inference.py", line 78, in sample_uncoditional_model
    res = model.sample_from_noise(
  File "/usrpath/data/openmmlab/mmgeneration/mmgen/models/gans/base_gan.py", line 166, in sample_from_noise
    outputs = _model(noise, num_batches=num_batches, **kwargs)
  File "/usrpath/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usrpath/data/openmmlab/mmgeneration/mmgen/models/architectures/stylegan/generator_discriminator_v2.py", line 340, in forward
    styles = [self.style_mapping(s) for s in styles]
  File "/usrpath/data/openmmlab/mmgeneration/mmgen/models/architectures/stylegan/generator_discriminator_v2.py", line 340, in <listcomp>
    styles = [self.style_mapping(s) for s in styles]
  File "/usrpath/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usrpath/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usrpath/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usrpath/data/openmmlab/mmgeneration/mmgen/models/architectures/stylegan/modules/styleganv2_modules.py", line 89, in forward
    x = self.activate(x, self.bias * self.lr_mul)
  File "/usrpath/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/fused_bias_leakyrelu.py", line 158, in fused_bias_leakyrelu
    return FusedBiasLeakyReLUFunction.apply(input, bias.to(input.dtype),
  File "/usrpath/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/fused_bias_leakyrelu.py", line 71, in forward
    out = ext_module.fused_bias_leakyrelu(
TypeError: fused_bias_leakyrelu(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: int, arg4: int, arg5: float, arg6: float) -> at::Tensor

Invoked with: tensor([[ 1.5543,  0.9359, -0.7516,  ...,  0.8526,  0.1092, -1.5828],
        [-0.4884, -0.5331,  0.0995,  ..., -1.1292,  0.7263,  0.0868],
        [ 1.8955, -0.2950, -0.6122,  ..., -1.5320,  0.3621, -0.0334],
        [-1.1611,  1.4324, -0.5950,  ..., -0.0754, -0.2390,  0.5369]],
       device='cuda:0'), tensor([ 2.1072e-02,  7.2350e-03, -7.3995e-03,  8.8704e-03,  1.2794e-02,
         5.6403e-03,  2.0907e-02,  3.6095e-02,  2.7718e-02,  2.5495e-02,
         5.5971e-02, -2.6303e-03, -1.9122e-02,  3.4960e-02, -9.9869e-04,
         5.4610e-02, -2.1504e-02, -7.6235e-04,  4.2148e-02,  2.9336e-02,
        -1.2010e-02,  2.6697e-02,  2.0704e-02,  1.7850e-02,  2.5822e-02,
         2.4205e-02,  9.2259e-03,  5.2766e-03, -9.7084e-03,  3.1917e-02,
         1.4420e-02,  1.9740e-02,  4.5503e-03, -1.3387e-03,  3.1348e-02,
         2.8662e-02,  2.1212e-02,  2.7612e-02,  2.7846e-02,  1.9240e-02,
         1.4399e-03,  2.4100e-02,  1.5192e-03,  2.1962e-02,  3.8593e-02,
         2.6981e-02,  2.3939e-02, -2.5659e-02,  1.8938e-02,  4.2813e-03,
         3.2460e-02, -6.4725e-03,  5.7439e-03, -8.2432e-03,  2.8644e-02,
         1.7430e-02,  1.6883e-02,  2.1885e-02, -3.7464e-02, -2.3679e-03,
        -2.0484e-02,  3.5609e-03, -3.3241e-02,  2.5305e-02,  8.8699e-03,
         1.0048e-02,  1.9374e-05,  4.6468e-02,  6.3671e-03,  2.8634e-02,
        -2.0427e-02,  2.0850e-02,  1.3230e-02,  1.4341e-02,  3.5405e-02,
         3.3669e-02,  7.0619e-03, -7.3995e-03,  1.5559e-02,  1.6781e-02,
         1.5602e-02,  4.9376e-03, -1.4243e-02, -3.6679e-04,  1.9603e-02,
        -1.4750e-02, -2.0574e-02,  2.7651e-02,  5.3985e-03,  2.2140e-02,
         3.8984e-02, -2.1741e-02,  1.4327e-02,  2.8988e-02,  3.2486e-02,
         1.6863e-02,  1.7482e-02, -1.1381e-02,  3.0547e-02,  1.9567e-02,
        -7.9459e-04, -1.0579e-02,  4.3845e-03,  1.4310e-02,  2.4147e-02,
         4.3581e-02,  1.3225e-02,  3.0805e-03, -7.5716e-03,  2.0421e-02,
         4.3091e-02, -7.6145e-03,  5.7272e-03,  1.6518e-02,  5.0934e-02,
         5.7350e-03,  2.5533e-02,  1.7434e-02,  2.7099e-02,  1.4430e-02,
         4.5475e-03, -6.0277e-03, -3.5998e-02,  3.2768e-02,  8.8244e-04,
        -4.2015e-02, -1.3836e-02, -2.7834e-02, -2.0692e-03,  5.6001e-02,
         1.5373e-02,  1.1584e-02, -1.6014e-02,  3.1709e-02,  4.5359e-02,
        -1.3453e-02,  2.9151e-02, -7.2418e-04,  4.8063e-02,  4.6696e-03,
        -1.0628e-02, -3.5622e-02, -2.7828e-02,  4.8612e-02,  8.2219e-03,
        -1.1421e-02,  9.2356e-04, -2.0823e-02,  3.5524e-03, -1.4194e-02,
         5.2389e-02,  2.9024e-02,  4.0951e-02,  1.6816e-02, -6.9830e-04,
         1.2723e-02,  9.0101e-03, -1.0772e-02,  4.1453e-02,  3.0848e-02,
        -4.0323e-03, -9.3071e-03, -2.5157e-03, -1.7072e-02, -6.3630e-03,
         4.7484e-02, -9.7196e-03,  4.4207e-04,  5.3285e-02, -1.3681e-02,
         3.6376e-02, -2.4833e-02, -1.7205e-02,  8.6541e-04, -4.9962e-03,
         2.2003e-02,  2.7286e-02,  4.3871e-02,  3.7229e-03,  1.1205e-02,
         6.5684e-03,  3.5262e-02,  1.9407e-02, -2.7542e-02, -1.4560e-03,
         3.1051e-02,  8.6826e-03, -6.7558e-03,  1.2897e-03, -8.2027e-03,
         3.5474e-02,  2.9025e-02,  8.3344e-03,  3.0252e-02, -1.0292e-02,
         2.1823e-02,  2.2295e-02,  2.3701e-02,  9.5861e-03, -5.9920e-03,
         2.4102e-02,  6.4874e-03,  4.5393e-03,  6.0186e-03,  1.2538e-03,
        -8.4845e-03,  4.8124e-03,  1.8087e-02,  2.9517e-02,  4.7770e-03,
         6.5807e-03,  2.3674e-02,  3.7929e-02,  2.2110e-02,  2.2780e-02,
         1.3864e-02,  7.1113e-03,  1.2022e-02, -5.3407e-03,  3.6154e-02,
         6.7236e-03,  2.8046e-02,  2.7828e-02,  9.8256e-03,  4.3182e-02,
         2.0617e-02,  4.5155e-02, -1.5414e-02,  1.5908e-02,  6.8419e-03,
         2.9496e-02, -3.1403e-02,  3.6277e-02,  4.6770e-02,  5.5999e-02,
         2.8341e-04, -1.6284e-03,  7.3653e-03,  9.8462e-03,  2.4935e-02,
         4.5824e-03, -1.0666e-02,  1.1739e-02,  3.6363e-02, -2.9184e-02,
         1.7379e-02,  2.3970e-02,  2.4238e-02, -8.9407e-03,  6.6026e-04,
        -2.2883e-02, -3.3076e-02, -4.4075e-03,  1.6711e-02,  1.3338e-02,
        -1.2148e-02, -2.3471e-02,  7.0922e-03,  3.0079e-02,  8.8431e-03,
         2.0569e-02,  1.0583e-02, -3.8945e-03,  2.9986e-02,  5.9738e-03,
         7.9658e-03, -1.5161e-02, -2.9107e-02,  4.6673e-03,  2.0985e-02,
        -3.4134e-02, -1.9778e-03,  1.3358e-02, -3.5385e-03,  6.8200e-03,
         4.1863e-02,  1.3161e-02,  3.3239e-03, -4.8689e-03, -5.6864e-03,
         2.4394e-02,  6.5547e-02, -1.8028e-02,  2.6225e-02, -1.0597e-02,
         1.8662e-02, -1.7158e-02,  5.9483e-03,  7.8847e-03, -5.3181e-02,
         1.9470e-02,  1.6042e-02, -3.6935e-03, -3.0404e-02,  2.3784e-02,
         5.2594e-02,  5.9842e-03, -9.9118e-03,  6.2297e-04, -5.0590e-03,
         1.3509e-02,  2.4367e-02, -1.5341e-02, -3.5737e-03, -2.9005e-02,
        -4.2906e-02, -4.0113e-03, -1.7275e-02,  7.2076e-03, -1.4392e-02,
         4.4198e-03,  3.9066e-02,  9.1157e-03,  1.9261e-02,  3.8205e-02,
         9.3444e-03, -3.2351e-03, -3.1751e-02,  5.6089e-04, -2.5561e-02,
         4.8151e-03, -1.8522e-02,  1.5201e-02,  2.7765e-02,  2.8825e-02,
         3.9171e-02,  4.6608e-03, -2.3405e-04,  1.9949e-05,  1.9330e-02,
         2.6645e-02,  3.3298e-02,  2.8010e-02,  1.0021e-02, -4.7764e-03,
         1.8138e-02,  2.0020e-02,  5.5121e-02,  1.0647e-02, -3.6136e-02,
         1.3342e-02,  3.2644e-02,  3.5566e-02,  2.8251e-03,  1.8185e-02,
         1.1187e-02,  1.1329e-02, -3.7697e-02,  3.0473e-02,  1.8692e-03,
         2.1232e-02, -1.1128e-02,  6.7449e-03, -2.1927e-02,  2.6531e-02,
         2.4637e-02, -1.2103e-02,  2.0931e-02,  4.8818e-03,  9.5352e-03,
         1.3082e-02,  1.2242e-02, -1.8965e-02, -8.8815e-03, -2.4578e-02,
         1.7757e-02,  4.3894e-02, -5.7756e-03, -2.0324e-02, -1.1204e-02,
         2.3646e-02,  2.3955e-03,  2.6433e-03,  3.0905e-02, -2.5491e-02,
         4.1358e-02,  2.3892e-02, -1.3900e-02,  6.1827e-03,  1.6889e-02,
         1.8942e-02, -1.9551e-02, -2.4444e-02,  2.8982e-02,  2.6768e-02,
         2.3272e-02,  9.3854e-03,  4.9806e-02,  1.5713e-03, -2.8103e-03,
         2.6112e-02, -1.9443e-02,  2.3675e-02,  5.1647e-04, -1.4187e-02,
         3.3832e-02,  1.6349e-02, -8.3935e-04,  2.6937e-02, -1.5575e-02,
        -6.4266e-03,  2.5762e-02,  3.4929e-02,  4.2691e-02,  2.2936e-02,
         1.3600e-02,  1.9131e-02,  1.4410e-02,  1.3022e-02,  8.8988e-03,
         2.0286e-02,  3.0822e-02,  4.5990e-02,  3.0429e-02,  1.4325e-02,
         3.0174e-02, -9.7151e-03,  6.1264e-03,  1.7919e-02,  1.1921e-02,
         1.1496e-02, -2.1060e-02, -2.1198e-03,  2.7974e-02, -1.4536e-02,
         2.8282e-02, -2.2916e-02,  3.0952e-02, -2.9149e-02,  4.8224e-04,
         1.2608e-02,  3.7351e-04, -1.9128e-02,  2.4483e-02,  4.7125e-03,
        -2.4219e-02,  6.6152e-03,  3.9150e-02, -7.7771e-03,  3.3208e-02,
        -3.4074e-02,  7.5642e-04,  4.7129e-02,  1.3904e-04, -1.0335e-03,
         3.3290e-02,  5.2648e-02,  7.3007e-03,  4.0760e-02, -1.8254e-02,
         5.3701e-03,  1.6878e-02,  4.3795e-03,  9.5917e-03,  1.6428e-02,
         3.7221e-02,  1.7113e-02,  1.0436e-02, -1.7236e-02,  2.2115e-02,
        -7.6049e-03, -8.7258e-04, -2.5602e-02,  2.0399e-02, -1.9864e-02,
        -6.1954e-03,  3.3585e-02,  9.5259e-03,  2.2930e-02,  1.7410e-02,
        -3.0388e-02,  5.9288e-03,  2.1480e-03,  3.6306e-02, -7.4481e-03,
         3.7329e-02,  2.2018e-02, -9.5370e-03,  1.2821e-02,  2.6528e-02,
         2.3349e-02,  2.2825e-02, -4.2607e-02,  7.9119e-03,  2.3603e-02,
         4.8039e-02,  3.9244e-02,  4.2007e-02,  7.2430e-03, -1.6995e-02,
         2.2379e-02, -3.1171e-03,  9.4846e-03,  4.4265e-03,  3.0305e-02,
        -1.5910e-02,  3.0286e-02, -2.3028e-02, -4.0660e-02,  4.5538e-03,
        -6.2878e-03, -1.1943e-02, -2.5031e-03,  2.4371e-02,  1.7945e-02,
        -1.4140e-03, -4.1711e-03,  1.9475e-02, -4.1921e-03,  4.0421e-03,
         6.0400e-03, -4.2922e-03], device='cuda:0'), tensor([], device='cuda:0'); kwargs: act=3, grad=0, alpha=0.2, scale=1.4142135623730951

**Comment by wj-data** [comment]
> Hi @wj-data , sorry about this bug. This is caused by the new MMCV version and we have fixed it yesterday. I suggest that you can use `mmcv-full==1.3.1` for stable training and inference.

thank you, it works fine now.
