### ISSUE TITLE
error

### ISSUE THREAD

**Issue by flynnamy** [open-mmlab/mmgeneration#292]
How to solve this erro?

AttributeError: 'MMDataParallel' object has no attribute 'reducer'

**Comment by LeoXing1996** [comment]
Please provide the command you execute and the full error info.

**Comment by huangjiyi** [comment]
Hi, @LeoXing1996 , I meet the same error. Here's some information that might be useful.

- Command: 
`python ./mmgeneration/tools/train.py configs/stylegan2/polyu.py --work-dir log/stylegan2_polyu --gpu-id 1`
- Error info: 
```
2022-05-22 21:48:23,227 - mmgen - INFO - Start running, host: hjy@ps, work_dir: /media/hjy/gan/log/stylegan2_polyu
2022-05-22 21:48:23,227 - mmgen - INFO - workflow: [('train', 10000)], max: 100002 iters
2022-05-22 21:48:23,228 - mmgen - INFO - Checkpoints will be saved to log/stylegan2_polyu/ckpt/stylegan2_polyu by HardDiskBackend.
Traceback (most recent call last):
  File "/media/hjy/gan/./mmgeneration/tools/train.py", line 228, in <module>
    main()
  File "/media/hjy/gan/./mmgeneration/tools/train.py", line 217, in main
    train_model(
  File "/media/hjy/gan/mmgeneration/mmgen/apis/train.py", line 207, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/media/hjy/gan/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/media/hjy/gan/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 207, in train
    kwargs.update(dict(ddp_reducer=self.model.reducer))
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MMDataParallel' object has no attribute 'reducer'
```
- Configs can be find in [https://github.com/open-mmlab/mmgeneration/issues/300](https://github.com/open-mmlab/mmgeneration/issues/300)
- Command `bash mmgeneration/tools/dist_train.sh configs/stylegan2/polyu.py 1 --work-dir log/stylegan2_polyu` can work. But if I already have a training program running and I try to run another training program, I get another error:
```
Traceback (most recent call last):
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 700, in run
    result = self._invoke_run(role)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 822, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 670, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 530, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(
RuntimeError: Address already in use
```

Thans a lot!
