### ISSUE TITLE
Error about running multiple training scripts at the same time

### ISSUE THREAD

**Issue by huangjiyi** [open-mmlab/mmgeneration#302]
Hi, I want to run multiple training scripts `dist_train.sh` at the same time for efficiency. But I get following error when I already have a training script running and try to run another training program.
```
Traceback (most recent call last):
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 700, in run
    result = self._invoke_run(role)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 822, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 670, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 530, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/hjy/miniconda3/envs/mmgen/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(
RuntimeError: Address already in use
```

**Comment by LeoXing1996** [comment]
You can add `PORT` at the beginning of your command manually to set the communication port for each experiment, e.g.
```shell
bash tools/dist_train.sh ${YOUR_ARGS_1}
PORT=23333 bash tools/dist_train.sh ${YOUR_ARGS_2}
PORT=66666 bash tools/dist_train.sh ${YOUR_ARGS_3}
```

**Comment by huangjiyi** [comment]
Thanks for your replying, @LeoXing1996 . it works. But now I have another problem that I can't specify the gpu id. 
I execute the command `PORT=23333 bash mmgeneration/tools/dist_train.sh config.py 1 --work-dir work_dir --gpu-id 1`, but gpu-0 is still used.

**Comment by LeoXing1996** [comment]
`gpu-id` argument is only used in non-DDP training, which is not applicable with `dist_train.sh`.
If you want to use the specific GPUs in DDP training, you can use the following command:
```shell
CUDA_VISIBLE_DEVICES=0,1 bash mmgeneration/tools/dist_train.sh config.py 2 --work-dir work_dir
CUDA_VISIBLE_DEVICES=2 PORT=23333 bash mmgeneration/tools/dist_train.sh config.py 1 --work-dir work_dir
```

**Comment by huangjiyi** [comment]
Thanks a lot! @LeoXing1996
