### ISSUE TITLE
how to train on windows& error:CalledProcessError: Command 'gcc --version | head -n1' returned non-zero exit status 255.

### ISSUE THREAD

**Issue by weiweilv1** [open-mmlab/mmgeneration#304]
I have successfully run the demo following the tutorial on windows,but i met this problem when i train  the strawberry dataset
python tools/train.py configs/styleganv2/stylegan2_c2_ffhq_256_b4x8_800k_strawberry.py  --work-dir work_dirs/experiments/stylegan2_strawberry 
tools/train.py:97: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as ne
eded.
  warnings.warn(
tools/train.py:107: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as n
eeded.
  warnings.warn(
'tail' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "tools/train.py", line 228, in <module>
    main()
  File "tools/train.py", line 179, in main
    env_info_dict = collect_env()
  File "d:\programdata\mmgenerate\mmgeneration\mmgen\utils\collect_env.py", line 50, in collect_env
    gcc = subprocess.check_output('gcc --version | head -n1', shell=True)
  File "D:\ProgramData\Anaconda3\envs\mmgenerate\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\ProgramData\Anaconda3\envs\mmgenerate\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gcc --version | head -n1' returned non-zero exit status 255.

**Comment by LeoXing1996** [comment]
This is caused by `gcc --version` output being different between Windows and Ubuntu.
We will fix this later. A temporary solution is to remove the following lines:
https://github.com/open-mmlab/mmgeneration/blob/6bce6ed0315438b3f7955019a2c6a64078cfd0e8/mmgen/utils/collect_env.py#L50-L52

**Comment by LeoXing1996** [comment]
This issue has been automatically closed because there has been no response to our request for more information from the original author.

**Comment by weiweilv1** [comment]
Thank you for your letter. According to your suggestion, the problem has been solved, but I met some other problems when I trained my data set on Windows.&nbsp; So I started Ubuntu, thank you for your help.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmgeneration"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 上午9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmgeneration] how to train on windows&amp; error:CalledProcessError: Command 'gcc --version | head -n1' returned non-zero exit status 255. (Issue #304)





 
Closed #304 as completed.
