### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by drnighthan** [open-mmlab/mmgeneration#376]
from mmgen.apis import init_model,sample_unconditional_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\BrendanDesktop\anaconda3\envs\openmmlab\lib\site-packages\mmgen\__init__.py", line 24, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.6.1 is used but incompatible. Please install mmcv>=1.3.0, <=1.5.0.

**Comment by drnighthan** [comment]
Then I install mmcv-full == 1.6.0.The error comes like this:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\brendandesktop\mmgeneration\mmgen\apis\__init__.py", line 2, in <module>
    from .inference import (init_model, sample_conditional_model,
  File "c:\users\brendandesktop\mmgeneration\mmgen\apis\inference.py", line 8, in <module>
    from mmgen.datasets.pipelines import Compose
  File "c:\users\brendandesktop\mmgeneration\mmgen\datasets\__init__.py", line 4, in <module>
    from .grow_scale_image_dataset import GrowScaleImgDataset
  File "c:\users\brendandesktop\mmgeneration\mmgen\datasets\grow_scale_image_dataset.py", line 8, in <module>
    from .pipelines import Compose
  File "c:\users\brendandesktop\mmgeneration\mmgen\datasets\pipelines\__init__.py", line 2, in <module>
    from .augmentation import (CenterCropLongEdge, Flip, NumpyPad,
  File "c:\users\brendandesktop\mmgeneration\mmgen\datasets\pipelines\augmentation.py", line 4, in <module>
    from mmcls.datasets import PIPELINES as CLS_PIPELINE
  File "C:\Users\BrendanDesktop\anaconda3\envs\openmmlab\lib\site-packages\mmcls\__init__.py", line 55, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=1.3.16, <=1.5.0.

**Comment by LeoXing1996** [comment]
You should install mmcv 1.5.0, e.g.,
```bash
pip install mmcv-full==1.5.0
```

**Comment by drnighthan** [comment]
For those who has the same error
Error:
from mmgen.apis import init_model,sample_unconditional_model
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\BrendanDesktop\anaconda3\envs\openmmlab\lib\site-packages\mmgen_init_.py", line 24, in
assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.6.1 is used but incompatible. Please install mmcv>=1.3.0, <=1.5.0.
My Solution:
Check the _init_.py in the mmgeneration/mmgen folder. Find the code "mmcv_maximum_version = '1.6.0'" and replace it to "mmcv_maximum_version = '1.6.1'"
