### ISSUE TITLE
RuntimeError: ModuleNotFoundError: No module named 'matplotlib.blocking_input'

### ISSUE THREAD

**Issue by darkbridge** [open-mmlab/mmgeneration#498]
**Describe the bug**
After I install mmgen, when I verify the installation, it occur ModuleNotFoundError: No module named 'matplotlib.blocking_input'.

**Reproduction**

1. What command or script did you run?

```none
from mmgen.apis import init_model, sample_unconditional_model
```

**Environment**
```
Start checking the installation of mmcv-full ...
CPU ops were compiled successfully.
CUDA ops were compiled successfully.
mmcv-full has been installed successfully.

Environment information:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA TITAN Xp
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (GCC) 5.5.0
PyTorch: 1.12.1+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu116
OpenCV: 4.7.0
MMCV: 1.5.0
MMCV Compiler: GCC 5.5
MMCV CUDA Compiler: 11.6
------------------------------------------------------------

>>> import mmgen
>>> mmgen.__version__
'0.5.0'
```
**Error traceback**

```none
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mi/workspace/mmgeneration/mmgen/apis/__init__.py", line 2, in <module>
    from .inference import (init_model, sample_conditional_model,
  File "/home/mi/workspace/mmgeneration/mmgen/apis/inference.py", line 8, in <module>
    from mmgen.datasets.pipelines import Compose
  File "/home/mi/workspace/mmgeneration/mmgen/datasets/__init__.py", line 4, in <module>
    from .grow_scale_image_dataset import GrowScaleImgDataset
  File "/home/mi/workspace/mmgeneration/mmgen/datasets/grow_scale_image_dataset.py", line 8, in <module>
    from .pipelines import Compose
  File "/home/mi/workspace/mmgeneration/mmgen/datasets/pipelines/__init__.py", line 2, in <module>
    from .augmentation import (CenterCropLongEdge, Flip, NumpyPad,
  File "/home/mi/workspace/mmgeneration/mmgen/datasets/pipelines/augmentation.py", line 4, in <module>
    from mmcls.datasets import PIPELINES as CLS_PIPELINE
  File "/home/mi/.local/lib/python3.8/site-packages/mmcls/datasets/__init__.py", line 2, in <module>
    from .base_dataset import BaseDataset
  File "/home/mi/.local/lib/python3.8/site-packages/mmcls/datasets/base_dataset.py", line 11, in <module>
    from mmcls.models.losses import accuracy
  File "/home/mi/.local/lib/python3.8/site-packages/mmcls/models/__init__.py", line 6, in <module>
    from .classifiers import *  # noqa: F401,F403
  File "/home/mi/.local/lib/python3.8/site-packages/mmcls/models/classifiers/__init__.py", line 2, in <module>
    from .base import BaseClassifier
  File "/home/mi/.local/lib/python3.8/site-packages/mmcls/models/classifiers/base.py", line 11, in <module>
    from mmcls.core.visualization import imshow_infos
  File "/home/mi/.local/lib/python3.8/site-packages/mmcls/core/visualization/__init__.py", line 1, in <module>
    from .image import (BaseFigureContextManager, ImshowInfosContextManager,
  File "/home/mi/.local/lib/python3.8/site-packages/mmcls/core/visualization/image.py", line 8, in <module>
    from matplotlib.blocking_input import BlockingInput
ModuleNotFoundError: No module named 'matplotlib.blocking_input'

```

**Comment by mymymy123** [comment]
Have you solved it yet？
