### ISSUE TITLE
An error in Verification

### ISSUE THREAD

**Issue by daiyuanm** [open-mmlab/mmgeneration#52]
Hello! Thank you for your work！

When I followed the [get_started.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs/get_started.md) for verification, an error occurred: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/hy-nas/mmgeneration/mmgen/apis/inference.py", line 78, in sample_uncoditional_model
    res = model.sample_from_noise(
  File "/hy-nas/mmgeneration/mmgen/models/gans/base_gan.py", line 167, in sample_from_noise
    outputs = _model(noise, num_batches=num_batches, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hy-nas/mmgeneration/mmgen/core/runners/fp16_utils.py", line 141, in new_func
    return old_func(*args, **kwargs)
  File "/hy-nas/mmgeneration/mmgen/models/architectures/stylegan/generator_discriminator_v2.py", line 369, in forward
    styles = [self.style_mapping(s) for s in styles]
  File "/hy-nas/mmgeneration/mmgen/models/architectures/stylegan/generator_discriminator_v2.py", line 369, in <listcomp>
    styles = [self.style_mapping(s) for s in styles]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hy-nas/mmgeneration/mmgen/models/architectures/stylegan/modules/styleganv2_modules.py", line 104, in forward
    x = self.linear(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 875, in _call_impl
    result = hook(self, input)
  File "/hy-nas/mmgeneration/mmgen/models/architectures/pggan/modules.py", line 67, in __call__
    setattr(module, self.name, self.compute_weight(module))
  File "/hy-nas/mmgeneration/mmgen/models/architectures/pggan/modules.py", line 59, in compute_weight
    weight = weight * torch.tensor(
RuntimeError: CUDA error: no kernel image is available for execution on the device
`
I tested the installed CUDA as shown below：
>>> import torch
>>> import torchvision
>>> print(torch.cuda.is_available())
True
>>> a = torch.Tensor(5,3)
>>> a = a.cuda()
>>> print (a)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In fact, I also did some experiments on the same platform before, and there was no such error. Could you give me some suggestions?

ps. I did not use anaconda to create a virtual environment， and my environment is like this:
```
Ubuntu 18.04
Python 3.8
PyTorch 1.8.1
CUDA 11.1
gcc version 7.5.0
mmcv-full-1.3.6
a rtx3090
```
 I see a closed issue (https://github.com/open-mmlab/mmgeneration/issues/4),  so I try:
```
import mmcv
from mmgen.apis import init_model, sample_uncoditional_model

config_file = 'configs/styleganv2/stylegan2_c2_lsun-church_256_b4x8_800k.py'
# you can download this checkpoint in advance and use a local file path.
checkpoint_file = 'https://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-church-config-f-official_20210327_172657-1d42b7d1.pth'
device = 'cpu'
# init a generatvie
model = init_model(config_file, checkpoint_file, device=device).cpu()
# sample images
fake_imgs = sample_uncoditional_model(model, 4)
```
the result is:
`Use load_from_http loader
2021-06-16 17:55:54,373 - mmgen - INFO - Switch to evaluation style mode: single
2021-06-16 17:55:54,374 - mmgen - INFO - Switch to evaluation style mode: single
`
I don’t know if this proves that the installation was successful.

**Comment by nbei** [comment]
Hi @daiyuanm , The verification in the CPU indicates the installation is successful in the CPU device.

However, there is also a bug in the GPU part, as shown in your issue. The bug in your GPU inference may be caused by the RTX3090. Currently, `mmcv-full` have not provided the correct version for RTX3090. You may need to compile the `mmcv-full` from scratch by yourself.

Since we do not have RTX3090, I'm sorry that I cannot compile it and check the correctness for you. If any questions in compiling `mmcv-full`, you can also leave comments here.

**Comment by wangruohui** [comment]
You can try compile mmcv-full yourself, with CUDA version >11 and environment variable `TORCH_CUDA_ARCH_LIST=8.6` set.

**Comment by daiyuanm** [comment]
Thank you all for your suggestions. I just tried @wangruohui‘s suggestion, but there are still errors.
`    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/hy-nas/mmcv/setup.py'"'"'; __file__='"'"'/hy-nas/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
`

Cause I am using a cloud server, I made the following changes.
`PyTorch 1.7.1 + CUDA 11.0`
Then everything went well without any errors.

**Comment by nbei** [comment]
> Thank you all for your suggestions. I just tried @wangruohui‘s suggestion, but there are still errors.
> ` ---------------------------------------- ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/hy-nas/mmcv/setup.py'"'"'; __file__='"'"'/hy-nas/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`
> 
> Cause I am using a cloud server, I made the following changes.
> `PyTorch 1.7.1 + CUDA 11.0`
> Then everything went well without any errors.

Could you tell me the cloud server you are using? We can have a try on it.
