### ISSUE TITLE
Verification failed in Win10

### ISSUE THREAD

**Issue by xqyd** [open-mmlab/mmgeneration#62]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmgeneration.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmgen/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
************************************************************************************************************
Have read aforementioned list and still could not fix the problem. The way to reproduce my problem follows：
1. install mmgeneration with following scripts:
conda create -n open-mmlab python=3.7 -y
conda activate open-mmlab

conda install pytorch==1.7.0 torchvision==0.8.0 cudatoolkit=10.1 -c pytorch -y

# install the latest mmcv
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html

# install mmgeneration
git clone https://github.com/open-mmlab/mmgeneration.git
cd mmgeneration
pip install -r requirements.txt
pip install -v -e .

2. run verification and found out 'from mmcv.ops import get_compiling_cuda_version, get_compiler_version' cause ImportError
(open-mmlab1) C:\Users\13456\mmgeneration>python
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mmcv.ops import get_compiling_cuda_version, get_compiler_version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\13456\anaconda3\envs\open-mmlab1\lib\site-packages\mmcv\ops\__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "C:\Users\13456\anaconda3\envs\open-mmlab1\lib\site-packages\mmcv\ops\bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "C:\Users\13456\anaconda3\envs\open-mmlab1\lib\site-packages\mmcv\utils\ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\13456\anaconda3\envs\open-mmlab1\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: 找不到指定的程序。

3. Tried this and could not get useful info
(open-mmlab1) C:\Users\13456\mmgeneration>python mmgen/utils/collect_env.py
'tail' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "mmgen/utils/collect_env.py", line 69, in <module>
    for name, val in collect_env().items():
  File "mmgen/utils/collect_env.py", line 44, in collect_env
    gcc = subprocess.check_output('gcc --version | head -n1', shell=True)
  File "C:\Users\13456\anaconda3\envs\open-mmlab1\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\13456\anaconda3\envs\open-mmlab1\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'gcc --version | head -n1' returned non-zero exit status 255.

**Comment by xqyd** [comment]
Solved by finding "mmcv_full-1.3.7-cp37-cp37m-win_amd64.whl",
delete it
uninstall mmcv-full
reinstall https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html which will build the "mmcv_full-1.3.7-cp37-cp37m-win_amd64.whl" in the same place again. But this time it works. So I guess it could something related to path/location.

BTW, always failed with "ModuleNotFoundError: No module named 'mmdet'" and had to "pip install mmdet" manually.
